FROM azul/zulu-openjdk-alpine:11-jre 
LABEL maintainer="steven.trescinski@gluo.be"
RUN adduser -h /app -Ds /bin/bash app-user
USER app-user
COPY ./target/shopping-list-*.jar /app/application.jar
WORKDIR /app
EXPOSE 8080
ENTRYPOINT [ "java", "-jar", "/app/application.jar", "--spring.profiles.active=hsqldb" ]
